### ISSUE TITLE
RTL languages

### ISSUE THREAD

**Issue by DeusExMachina1993** [petermeissner/crossword.r#12]
is this package working with RTL languages?
can change direction to the left?

**Comment by petermeissner** [comment]
No, currently this doesn't work with right to left languages ... Although,
it very well could work ... In principle it should 'only' be a matter of
switching the direction words are out on the grid.



mreza mnejad <notifications@github.com> schrieb am Di., 11. Sep. 2018,
16:27:

**Comment by DeusExMachina1993** [comment]
sometimes just so simple!
thanks.
